### ISSUE TITLE
crashes when loading world :( 

### ISSUE THREAD

**Issue by heichoukun** [DavidGmc18/Nature_Arise_PUBLIC#8]
[crash-2024-05-21_19.15.34-server.txt](https://github.com/DavidGmc18/Nature_Arise_PUBLIC/files/15396417/crash-2024-05-21_19.15.34-server.txt)
[crash-2024-05-21_19.39.42-server.txt](https://github.com/DavidGmc18/Nature_Arise_PUBLIC/files/15396418/crash-2024-05-21_19.39.42-server.txt)

It switches up which biome crashes it, but it seems like the new biomes conflict with default minecraft biomes when generating worlds.

**Comment by DavidGmc18** [comment]
That issue is caused by features in biomes being out of order. Unfortunately, I haven't been able to replicate your issue, nor have I found anything out of order in related jsons. I believe this is not a NA issue but rather some kind of incompatibility, but I can't say for sure. Are you using any mods that modify vanilla biomes, datapacks, texture packs, or anything else that could alter jsons?
